services:
  app:
    image: dockerrizedappsample
    container_name: dockerrizedappsample_app
    build:
      context: .
      dockerfile: DockerizedAppSample/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: dockerrizedappsample_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
