name: CI

on:
  push:
    branches:
      – main
  pull_request:
    branches:
      – main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v4   
    - uses: docker/setup-buildx-action@v3 
    - uses: docker/setup-qemu-action@v1
    - uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: user/repo:latest    
    run: docker-compose up -d
